Repository Lab41/cyphercat, pull requests merged in 2018-12, with the labels that each got.

#54 Standardizes datasets objects, model loading. Recovers some docs.
  cyphercat/load_data.py
  cyphercat/metrics.py
  cyphercat/models.py
  cyphercat/train.py
  cyphercat/utils/config_utils.py
  cyphercat/utils/file_utils.py
  cyphercat/utils/svc_utils.py
  cyphercat/utils/visualize_utils.py
  docs/checklist.md
  docs/source/_static/Example-Fooling.png
  docs/source/_static/Example-Invert.png
  docs/source/_static/cyphercat_logo3_spc.png
  docs/source/_static/fork-button.png
  docs/source/_static/new-issue-button.png
  docs/source/_static/open-new-issue.png
  docs/source/_static/pull-request-button.png
  docs/source/api.rst
  docs/source/contributing.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/overview.rst
  docs/source/why.rst
  scripts/configs/lfw.yml
  scripts/test_train_lfw.py
Labels: Documentation, enhancement

#52 Adds notebook with 2 defensive strategies
  Defense_baselines/Membership_Inference/ml_leaks/ML-Leaks(3)_vs_distillation.ipynb
  Defense_baselines/Membership_Inference/ml_leaks/images/ML_leaks3_vs_VGG11.png
  Defense_baselines/Membership_Inference/ml_leaks/images/ML_leaks3_vs_distilled.png
  Defense_baselines/Membership_Inference/ml_leaks/images/ML_leaks3_vs_distilled_at20_1.png
Labels: enhancement

#55 Adds attack
  cyphercat/__init__.py
  cyphercat/attacks.py
Labels: enhancement

#56 Adds pytest to API checklist. Adds PR checklist template for users.
  .github/PULL_REQUEST_TEMPLATE.md
  cyphercat/definitions.py
  cyphercat/tests/__init__.py
  docs/checklist.md
Labels: Documentation

#59 Implements libri_dataset and splitting
  cyphercat/__init__.py
  cyphercat/datadefs/__init__.py
  cyphercat/datadefs/libri_dataset.py
Labels: enhancement

#60 Fixes bug introduced in commit 3114be5e874b27340b32ba423e02d8ac95ac193b
  Utils/train.py
Labels: bug

#58 Improve some docstrings. Accepts major flake8 checks of api base-code.
  cyphercat/attacks.py
  cyphercat/load_data.py
  cyphercat/metrics.py
  cyphercat/models.py
  cyphercat/train.py
  cyphercat/utils/config_utils.py
  cyphercat/utils/file_utils.py
  cyphercat/utils/svc_utils.py
  cyphercat/utils/utils.py
  cyphercat/utils/visualize_utils.py
  docs/source/_static/Cyphercat_full-color-logo.png
  docs/source/_static/Cyphercat_red-logo.png
  scripts/test_train_lfw.py
Labels: Documentation, enhancement

#62 Adds data split diagram for docs
  docs/source/_static/audio_splits_diagram.png
  docs/source/_static/data_splits_diagram.svg
  docs/source/_static/data_splits_table.png
  docs/source/_static/image_splits_diagram.png
Labels: Documentation

#63 Relative paths used in splitter, adds pandas to requirements
  Datasets/splits/libri-train-clean-100/READE.md
  cyphercat/datadefs/libri_dataset.py
  cyphercat/tests/test_libri_load.py
  requirements.txt
Labels: enhancement

#64 Moves LFW dataset class to datadefs directory
  cyphercat/__init__.py
  cyphercat/datadefs/__init__.py
  cyphercat/datadefs/lfw_dataset.py
  cyphercat/load_data.py
Labels: Documentation, enhancement
