Repository Lab41/cyphercat, pull requests merged in 2018-11, with the labels that each got.

#34 Adding pythonic ignore lines to .gitignore
  .gitignore
  cyphercat/__init__.py
  cyphercat/__version__.py
  cyphercat/load_data.py
  cyphercat/metrics.py
  cyphercat/models.py
  cyphercat/utils/__init__.py
  cyphercat/utils/config_utils.py
  cyphercat/utils/file_utils.py
  cyphercat/utils/svc_utils.py
  cyphercat/utils/utils.py
  docs/checklist.md
  requirements.txt
  scripts/configs/cifar-10.yml
  scripts/configs/cifar-100.yml
  scripts/configs/config.yml
  scripts/configs/lfw.yml
  scripts/configs/tiny-imagenet.yml
  scripts/test_load.py
  setup.py
Labels: enhancement, help wanted

#38 Adding interim license file, preps for improved docs
  .github/CONTRIBUTING.md
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSE
  docs/checklist.md
  docs/source/_static/Example-Fooling.png
  docs/source/_static/Example-Invert.png
  docs/source/_static/cyphercat_logo3_spc.png
  scripts/configs/cifar-10.yml
  scripts/configs/cifar-100.yml
Labels: Documentation

#39 Changing license to apache 2
  .github/PULL_REQUEST_TEMPLATE.md
  LICENSE
Labels: Documentation

#46 Personalized transformation and functionality
  Utils/models.py
  Utils/transformations.py
Labels: enhancement

#47 First standalone runtime script + webdoc structure
  cyphercat/__init__.py
  cyphercat/definitions.py
  cyphercat/load_data.py
  cyphercat/train.py
  cyphercat/utils/config_utils.py
  cyphercat/utils/file_utils.py
  docs/checklist.md
  docs/source/_static/fork-button.png
  docs/source/_static/new-issue-button.png
  docs/source/_static/open-new-issue.png
  docs/source/_static/pull-request-button.png
  docs/source/api.rst
  docs/source/contributing.rst
  docs/source/index.rst
  docs/source/installation.rst
  docs/source/overview.rst
  docs/source/why.rst
  requirements.txt
  scripts/test_train_lfw.py
Labels: Documentation, enhancement
